services:
#    card_maker.example:
#        class: CardMakerBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    cardmaker.handler.card_generate:
        class: CardMakerBundle\Handler\CardGenerate

